# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

User.create!(username: "test", password: "password")

Board.create!(user_id: 1, title: "To Dos")
Board.create!(user_id: 1, title: "Life Goals")
Board.create!(user_id: 1, title: "Travel Bucket List")
Board.create!(user_id: 1, title: "Books to Read")
Board.create!(user_id: 1, title: "Media to Watch")

List.create!(board_id: 1, title: "Learn C++", ord: 1)
List.create!(board_id: 1, title: "Learn Python", ord: 2)
List.create!(board_id: 2, title: "Buy a home in San Francisco", ord: 1)
List.create!(board_id: 2, title: "Start a business", ord: 2)
List.create!(board_id: 3, title: "Europe Bucket List", ord: 1)
List.create!(board_id: 3, title: "Other Bucket List", ord: 2)
List.create!(board_id: 4, title: "Non-Fiction", ord: 1)
List.create!(board_id: 4, title: "Fiction", ord: 2)
List.create!(board_id: 5, title: "Movies", ord: 1)
List.create!(board_id: 5, title: "TV Shows", ord: 2)

Card.create!(list_id: 1, description: "Study pointers", ord: 1)
Card.create!(list_id: 1, description: "Study garbage collection", ord: 2)
Card.create!(list_id: 1, description: "Read The C Programming Language", ord: 3)
Card.create!(list_id: 1, description: "Read The Structure and Interpretation of Computer Programs", ord: 4)
Card.create!(list_id: 1, description: "Work on projects in C++", ord: 5)
Card.create!(list_id: 2, description: "Learn Django", ord: 1)
Card.create!(list_id: 2, description: "Learn Flask", ord: 2)
Card.create!(list_id: 2, description: "Take Coursera Python course", ord: 3)
Card.create!(list_id: 2, description: "Find a good Python book to read", ord: 4)
Card.create!(list_id: 2, description: "Build a browser game in Python", ord: 5)
Card.create!(list_id: 3, description: "Find a good-paying job", ord: 1)
Card.create!(list_id: 3, description: "Save money!", ord: 2)
Card.create!(list_id: 3, description: "Work harder to get a promotion", ord: 3)
Card.create!(list_id: 3, description: "Find a girlfriend with a good, stable job", ord: 4)
Card.create!(list_id: 3, description: "Wait forever for prices to become reasonable", ord: 5)
Card.create!(list_id: 4, description: "Get 3-4 years of work experience", ord: 1)
Card.create!(list_id: 4, description: "Apply to business school?", ord: 2)
Card.create!(list_id: 4, description: "Apply to Y Combinator?", ord: 3)
Card.create!(list_id: 4, description: "Find a talented group of friends to work with", ord: 4)
Card.create!(list_id: 4, description: "Spend years thinking of a good idea", ord: 5)
Card.create!(list_id: 5, description: "Croatia", ord: 1)
Card.create!(list_id: 5, description: "Madrid", ord: 2)
Card.create!(list_id: 5, description: "Skiing in the Alps", ord: 3)
Card.create!(list_id: 5, description: "Santorini", ord: 4)
Card.create!(list_id: 5, description: "Italy (especially Florence)", ord: 5)
Card.create!(list_id: 6, description: "African Serengeti", ord: 1)
Card.create!(list_id: 6, description: "Brazil & Argentina", ord: 2)
Card.create!(list_id: 6, description: "Tibet", ord: 3)
Card.create!(list_id: 6, description: "Jerusalem", ord: 4)
Card.create!(list_id: 6, description: "Cairo", ord: 5)
Card.create!(list_id: 7, description: "An Eternal Golden Braid", ord: 1)
Card.create!(list_id: 7, description: "Nietzsche", ord: 2)
Card.create!(list_id: 7, description: "Einstein Biography", ord: 3)
Card.create!(list_id: 7, description: "The Economics of Life", ord: 4)
Card.create!(list_id: 7, description: "Keynes Hayek", ord: 5)
Card.create!(list_id: 8, description: "Murakami books", ord: 1)
Card.create!(list_id: 8, description: "Nabokov books", ord: 2)
Card.create!(list_id: 8, description: "100 Years of Solitude", ord: 3)
Card.create!(list_id: 8, description: "The Brothers Karamazov", ord: 4)
Card.create!(list_id: 8, description: "The Invisible Man", ord: 5)
Card.create!(list_id: 9, description: "The Theory of Everything", ord: 1)
Card.create!(list_id: 9, description: "Gone Girl", ord: 2)
Card.create!(list_id: 9, description: "Straight Out of Compton", ord: 3)
Card.create!(list_id: 9, description: "The Imitation Game", ord: 4)
Card.create!(list_id: 9, description: "Grand Budapest Hotel", ord: 5)
Card.create!(list_id: 10, description: "Game of Thrones", ord: 1)
Card.create!(list_id: 10, description: "Silicon Valley", ord: 2)
Card.create!(list_id: 10, description: "Suits", ord: 3)
Card.create!(list_id: 10, description: "Orange Is the New Black", ord: 4)
Card.create!(list_id: 10, description: "Fresh Off the Boat", ord: 5)