# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

User.create!(username: "test", password: "password")

Board.create!(user_id: 1, title: "To Dos")
Board.create!(user_id: 1, title: "Life Goals")
Board.create!(user_id: 1, title: "Travel Bucket List")
Board.create!(user_id: 1, title: "Books to Read")
Board.create!(user_id: 1, title: "Media to Watch")

List.create!(board_id: 1, title: "Learn C++", ord: 1)
List.create!(board_id: 1, title: "Learn Python", ord: 2)
List.create!(board_id: 2, title: "Buy a home in San Francisco", ord: 1)
List.create!(board_id: 2, title: "Start a business", ord: 2)
List.create!(board_id: 3, title: "Europe Bucket List", ord: 1)
List.create!(board_id: 3, title: "Other Bucket List", ord: 2)
List.create!(board_id: 4, title: "Non-Fiction", ord: 1)
List.create!(board_id: 4, title: "Fiction", ord: 2)
List.create!(board_id: 5, title: "Movies", ord: 1)
List.create!(board_id: 5, title: "TV Shows", ord: 2)

Card.create!(list_id: 1, title: "Study pointers", description: "sample description", ord: 1)
Card.create!(list_id: 1, title: "Study garbage collection", description: "sample description", ord: 2)
Card.create!(list_id: 1, title: "Read The C Programming Language", description: "sample description", ord: 3)
Card.create!(list_id: 1, title: "Read The Structure and Interpretation of Computer Programs", description: "sample description", ord: 4)
Card.create!(list_id: 1, title: "Work on projects in C++", description: "sample description", ord: 5)
Card.create!(list_id: 2, title: "Learn Django", description: "sample description", ord: 1)
Card.create!(list_id: 2, title: "Learn Flask", description: "sample description", ord: 2)
Card.create!(list_id: 2, title: "Take Coursera Python course", description: "sample description", ord: 3)
Card.create!(list_id: 2, title: "Find a good Python book to read", description: "sample description", ord: 4)
Card.create!(list_id: 2, title: "Build a browser game in Python", description: "sample description", ord: 5)
Card.create!(list_id: 3, title: "Find a good-paying job", description: "sample description", ord: 1)
Card.create!(list_id: 3, title: "Save money!", description: "sample description", ord: 2)
Card.create!(list_id: 3, title: "Work harder to get a promotion", description: "sample description", ord: 3)
Card.create!(list_id: 3, title: "Find a girlfriend with a good, stable job", description: "sample description", ord: 4)
Card.create!(list_id: 3, title: "Wait forever for prices to become reasonable", description: "sample description", ord: 5)
Card.create!(list_id: 4, title: "Get 3-4 years of work experience", description: "sample description", ord: 1)
Card.create!(list_id: 4, title: "Apply to business school?", description: "sample description", ord: 2)
Card.create!(list_id: 4, title: "Apply to Y Combinator?", description: "sample description", ord: 3)
Card.create!(list_id: 4, title: "Find a talented group of friends to work with", description: "sample description", ord: 4)
Card.create!(list_id: 4, title: "Spend years thinking of a good idea", description: "sample description", ord: 5)
Card.create!(list_id: 5, title: "Croatia", description: "sample description", ord: 1)
Card.create!(list_id: 5, title: "Madrid", description: "sample description", ord: 2)
Card.create!(list_id: 5, title: "Skiing in the Alps", description: "sample description", ord: 3)
Card.create!(list_id: 5, title: "Santorini", description: "sample description", ord: 4)
Card.create!(list_id: 5, title: "Italy (especially Florence)", description: "sample description", ord: 5)
Card.create!(list_id: 6, title: "African Serengeti", description: "sample description", ord: 1)
Card.create!(list_id: 6, title: "Brazil & Argentina", description: "sample description", ord: 2)
Card.create!(list_id: 6, title: "Tibet", description: "sample description", ord: 3)
Card.create!(list_id: 6, title: "Jerusalem", description: "sample description", ord: 4)
Card.create!(list_id: 6, title: "Cairo", description: "sample description", ord: 5)
Card.create!(list_id: 7, title: "An Eternal Golden Braid", description: "sample description", ord: 1)
Card.create!(list_id: 7, title: "Nietzsche", description: "sample description", ord: 2)
Card.create!(list_id: 7, title: "Einstein Biography", description: "sample description", ord: 3)
Card.create!(list_id: 7, title: "The Economics of Life", description: "sample description", ord: 4)
Card.create!(list_id: 7, title: "Keynes Hayek", description: "sample description", ord: 5)
Card.create!(list_id: 8, title: "Murakami books", description: "sample description", ord: 1)
Card.create!(list_id: 8, title: "Nabokov books", description: "sample description", ord: 2)
Card.create!(list_id: 8, title: "100 Years of Solitude", description: "sample description", ord: 3)
Card.create!(list_id: 8, title: "The Brothers Karamazov", description: "sample description", ord: 4)
Card.create!(list_id: 8, title: "The Invisible Man", description: "sample description", ord: 5)
Card.create!(list_id: 9, title: "The Theory of Everything", description: "sample description", ord: 1)
Card.create!(list_id: 9, title: "Gone Girl", description: "sample description", ord: 2)
Card.create!(list_id: 9, title: "Straight Out of Compton", description: "sample description", ord: 3)
Card.create!(list_id: 9, title: "The Imitation Game", description: "sample description", ord: 4)
Card.create!(list_id: 9, title: "Grand Budapest Hotel", description: "sample description", ord: 5)
Card.create!(list_id: 10, title: "Game of Thrones", description: "sample description", ord: 1)
Card.create!(list_id: 10, title: "Silicon Valley", description: "sample description", ord: 2)
Card.create!(list_id: 10, title: "Suits", description: "sample description", ord: 3)
Card.create!(list_id: 10, title: "Orange Is the New Black", description: "sample description", ord: 4)
Card.create!(list_id: 10, title: "Fresh Off the Boat", description: "sample description", ord: 5)
